import { useState } from "react";
import { cloneRepo, analyzeRepoStream } from "../api/apiClient";

const PIPELINE_STEPS = [
  { node: "ingest", label: "Scanning repository and chunking code" },
  { node: "embed", label: "Generating embeddings and indexing" },
  { node: "architecture", label: "Writing architecture overview" },
  { node: "code_analysis", label: "Running static analysis" },
];

function RepoUpload({ onAnalysisComplete, recentRepos = [], onSelectRecent }) {
  const [repoUrl, setRepoUrl] = useState("");
  const [githubToken, setGithubToken] = useState("");
  const [showTokenField, setShowTokenField] = useState(false);
  const [loading, setLoading] = useState(false);
  const [completedSteps, setCompletedSteps] = useState([]);
  const [error, setError] = useState("");

  const handleAnalyze = async () => {
    if (!repoUrl.trim()) {
      setError("Enter a GitHub repo URL first.");
      return;
    }

    setError("");
    setLoading(true);
    setCompletedSteps([]);

    try {
      const cloneRes = await cloneRepo(repoUrl.trim(), githubToken.trim());
      const repoName = cloneRes.data.repo_name;

      await new Promise((resolve) => {
        analyzeRepoStream(repoName, {
          onProgress: (event) => {
            setCompletedSteps((prev) => [...prev, event.node]);
          },
          onComplete: (result) => {
            setLoading(false);
            onAnalysisComplete({ repoName, ...result });
            resolve();
          },
          onError: (message) => {
            setError(message || "Something went wrong. Check the backend logs.");
            setLoading(false);
            resolve();
          },
        });
      });
    } catch (err) {
      setError(err.response?.data?.detail || "Something went wrong. Check the backend logs.");
      setLoading(false);
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === "Enter" && !loading) handleAnalyze();
  };

  return (
    <div className="app-shell">
      <div className="app-header">
        <p className="app-title">AI software engineer agent</p>
        <div className="brand-row">
          <svg className="brand-icon" viewBox="0 0 24 24" fill="none" stroke="#5b8def" strokeWidth="1.6">
            <path d="M9 6l-6 6 6 6" strokeLinecap="round" strokeLinejoin="round" />
            <path d="M15 6l6 6-6 6" strokeLinecap="round" strokeLinejoin="round" />
            <path d="M13 4l-2 16" strokeLinecap="round" strokeLinejoin="round" opacity="0.5" />
          </svg>
          <span className="brand-name">Code<span>Sense</span> AI</span>
        </div>
        <h1 className="app-lede">Understand any codebase in seconds</h1>
        <p className="app-sub">Paste a public (or private) GitHub repo. Get architecture, docs, and tests — generated by AI agents.</p>
      </div>

      <div className="terminal-input-row">
        <div className="terminal-input-wrap">
          <span className="terminal-prompt">&gt;</span>
          <input
            className="terminal-input"
            type="text"
            placeholder="github.com/username/repo"
            value={repoUrl}
            onChange={(e) => setRepoUrl(e.target.value)}
            onKeyPress={handleKeyPress}
            disabled={loading}
          />
        </div>
        <button
          className={`btn-primary ${loading ? "scanning" : ""}`}
          onClick={handleAnalyze}
          disabled={loading}
        >
          {loading ? "Analyzing..." : "Analyze repo"}
        </button>
      </div>

      <div style={{ textAlign: "center", marginTop: 10 }}>
        <button
          type="button"
          className="link-button"
          onClick={() => setShowTokenField((v) => !v)}
          disabled={loading}
        >
          {showTokenField ? "Hide private repo option" : "Analyzing a private repo?"}
        </button>
      </div>

      {showTokenField && (
        <div className="terminal-input-row" style={{ marginTop: 8 }}>
          <div className="terminal-input-wrap">
            <span className="terminal-prompt">🔒</span>
            <input
              className="terminal-input"
              type="password"
              placeholder="GitHub personal access token (used once, never stored)"
              value={githubToken}
              onChange={(e) => setGithubToken(e.target.value)}
              disabled={loading}
            />
          </div>
        </div>
      )}

      {loading && (
        <div className="progress-steps" style={{ maxWidth: 460, margin: "20px auto 0" }}>
          {PIPELINE_STEPS.map((step) => {
            const done = completedSteps.includes(step.node);
            const isCurrent = !done && completedSteps.length === PIPELINE_STEPS.findIndex((s) => s.node === step.node);
            const stateClass = done ? "done" : isCurrent ? "current" : "";
            return (
              <div key={step.node} className={`progress-step ${stateClass}`}>
                <span className="step-marker">{done ? "✓" : isCurrent ? "…" : ""}</span>
                <span>{step.label}</span>
              </div>
            );
          })}
        </div>
      )}

      {error && <p className="status-line error">{error}</p>}

      {!loading && recentRepos.length > 0 && (
        <div className="panel panel--overview" style={{ maxWidth: 460, margin: "32px auto 0" }}>
          <p className="panel-title"><span className="dot" /> Recent repos</p>
          <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
            {recentRepos.slice(0, 5).map((repo) => (
              <button
                key={repo.repo_name}
                className="recent-item"
                onClick={() => onSelectRecent(repo.repo_name)}
              >
                <span className="recent-name">{repo.repo_name}</span>
                <span className="recent-badge">{repo.total_chunks} chunks</span>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default RepoUpload;
