from app.agents.doc_generator_agent import generate_readme, generate_documentation, explain_code_snippet
from app.models.query_schema import CodeSnippetRequest
from fastapi import APIRouter, HTTPException, Response
import os

from app.models.repo_schema import RepoIngestRequest
from app.ingestion.chunker import chunk_repo
from app.agents.doc_generator_agent import generate_readme, generate_documentation
from app.agents.metrics_agent import generate_eval_metrics, format_eval_metrics_markdown
from app.memory import session_store

router = APIRouter()


@router.post("/docs/readme")
def get_readme(request: RepoIngestRequest):
    repo_path = os.path.join("cloned_repos", request.repo_name)
    if not os.path.exists(repo_path):
        raise HTTPException(status_code=404, detail="Repo not found. Clone it first.")

    chunks = chunk_repo(repo_path)
    readme = generate_readme(request.repo_name, chunks)

    return {"repo_name": request.repo_name, "readme": readme}


@router.post("/docs/function")
def get_function_doc(request: RepoIngestRequest, function_name: str):
    repo_path = os.path.join("cloned_repos", request.repo_name)
    if not os.path.exists(repo_path):
        raise HTTPException(status_code=404, detail="Repo not found. Clone it first.")

    chunks = chunk_repo(repo_path)
    clean_name = function_name.strip()
    match = next((c for c in chunks if clean_name.lower() in c["name"].lower()), None)

    if not match:
        raise HTTPException(status_code=404, detail=f"Function/class '{clean_name}' not found.")

    doc = generate_documentation(match)
    return {"name": match["name"], "documentation": doc}
@router.post("/docs/explain-snippet")
def explain_snippet(request: CodeSnippetRequest):
    if not request.code.strip():
        raise HTTPException(status_code=400, detail="No code provided.")

    explanation = explain_code_snippet(request.code, request.language)
    return {"explanation": explanation}


@router.get("/docs/export/{repo_name}")
def export_repo_docs(repo_name: str):
    """
    Bundles this repo's architecture overview, code analysis summary, and
    evaluation/metrics into a single downloadable Markdown file.
    """
    analysis = session_store.get_analysis(repo_name)
    if not analysis:
        raise HTTPException(status_code=404, detail="No analysis found for this repo. Analyze it first.")

    metrics = generate_eval_metrics(repo_name)
    metrics_section = format_eval_metrics_markdown(metrics)

    content = f"""# {repo_name} — CodeSense AI Report

_Generated by CodeSense AI._

## Architecture Overview

{analysis.get('readme') or '_No architecture overview available._'}

## Code Analysis Summary

{analysis.get('code_issues_summary') or '_No code analysis available._'}

{metrics_section}
"""

    filename = f"{repo_name}-codesense-report.md"
    return Response(
        content=content,
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )